// Aphorismen aus "Excellent Advice for Living" von Kevin Kelly (2023, Viking).
// Quelle: kk.org/thetechnium. Buch verfasst von Kevin Kelly an seinem 68. Geburtstag.
// Hier extrahiert fuer den Daily-Advice-Widget — strikt nur fuer persoenlichen Gebrauch.

export interface AdviceSeed {
  text: string;
  category: string;
}

const C = {
  LEARN: "Lernen",
  WORK: "Arbeit",
  RELATIONS: "Beziehungen",
  MONEY: "Geld",
  CREATIVITY: "Kreativitaet",
  HEALTH: "Gesundheit",
  TRAVEL: "Reisen",
  PRACTICAL: "Praktisch",
  WISDOM: "Lebensweisheit",
  FAMILY: "Familie",
} as const;

export const ADVICE_SEED: AdviceSeed[] = [
  { text: "Learn how to learn from those you disagree with or even offend you. See if you can find the truth in what they believe.", category: C.LEARN },
  { text: "Being enthusiastic is worth 25 IQ points.", category: C.WISDOM },
  { text: "Listening well is a superpower. While listening to someone you love keep asking them “Is there more?” until there is no more.", category: C.RELATIONS },
  { text: "Always demand a deadline because it weeds out the extraneous and the ordinary. A deadline prevents you from trying to make it perfect so you have to make it different. Different is better.", category: C.WORK },
  { text: "Don’t be afraid to ask a question that may sound stupid because 99% of the time everyone else is thinking of the same question and is too embarrassed to ask it.", category: C.LEARN },
  { text: "Prototype your life. Try stuff instead of making grand plans.", category: C.WISDOM },
  { text: "When you forgive others they may not notice but you will heal. Forgiveness is not something we do for others; it is a gift to ourselves.", category: C.WISDOM },
  { text: "The fact that you “can’t do” something can be embarrassing. But if you are “learning to do” something that is admirable. There are only tiny baby steps between can’t and learning.", category: C.LEARN },
  { text: "Don’t measure your life with someone else’s ruler.", category: C.WISDOM },
  { text: "When someone tells you what ticks them off they are telling you what makes them tick.", category: C.RELATIONS },
  { text: "Collecting things benefits you only if you display your collection prominently and share it in joy with others. The opposite of this is hoarding.", category: C.WISDOM },
  { text: "Taking a break is not a sign of weakness but a sign of strength.", category: C.HEALTH },
  { text: "A major part of travel is to leave stuff behind. The more you leave behind the further you will advance.", category: C.TRAVEL },
  { text: "You don’t have to attend every argument you are invited to.", category: C.RELATIONS },
  { text: "A worthy goal for a year is to learn enough about a subject so that you can’t believe how ignorant you were a year earlier.", category: C.LEARN },
  { text: "You can’t reason someone out of a notion that they didn’t reason themselves into.", category: C.WISDOM },
  { text: "Gratitude will unlock all other virtues and is something you can get better at.", category: C.WISDOM },
  { text: "When you are anxious because of your to-do list take comfort in your have-done list.", category: C.HEALTH },
  { text: "Treating a person to a meal never fails and is so easy to do. It’s powerful with old friends and a great way to make new friends.", category: C.RELATIONS },
  { text: "Pain is inevitable. Suffering is optional.", category: C.WISDOM },
  { text: "If you are looking for something in your house and you finally find it when you’re done with it don’t put it back where you found it. Put it back where you first looked for it.", category: C.PRACTICAL },
  { text: "Movement plus variety equals health.", category: C.HEALTH },
  { text: "Never use a credit card for credit. The only kind of credit, or debt that is acceptable is debt to acquire something whose exchange value is extremely likely to increase like a home. The exchange value of most things diminishes or vanishes the moment you purchase them. Don’t be in debt to losers.", category: C.MONEY },
  { text: "A great way to understand yourself is to seriously reflect on everything you find irritating in others.", category: C.WISDOM },
  { text: "The advantage of a ridiculously ambitious goal is that it sets the bar very high so even if your effort falls short it may exceed an ordinary success.", category: C.WORK },
  { text: "When you give away 10% of your income you lose 10% of your purchasing power which is minor compared to the 110% increase in happiness you will gain.", category: C.MONEY },
  { text: "The best way to learn anything is to try to teach what you know.", category: C.LEARN },
  { text: "Whenever you have a choice between being right or being kind be kind. No exceptions. Don’t confuse kindness with weakness.", category: C.RELATIONS },
  { text: "We lack rites of passage. Create a memorable family ceremony when your child reaches legal adulthood between eighteen and twenty-one. This moment will become a significant touchstone in their life.", category: C.FAMILY },
  { text: "The best way to get to yes in a negotiation is to truly understand what yes means for the other party.", category: C.WORK },
  { text: "Recipe for greatness: Become just a teeny bit better than you were last year. Repeat every year.", category: C.WORK },
  { text: "Draw to discover what you see. Write to discover what you think.", category: C.CREATIVITY },
  { text: "Whenever you can’t decide which path to take pick the one that produces change.", category: C.WISDOM },
  { text: "The quickest checkout line will be the one with the fewest people no matter the size of their carts.", category: C.PRACTICAL },
  { text: "Choose not to be outraged today.", category: C.WISDOM },
  { text: "Habit is far more dependable than inspiration. Make progress by making habits. Don’t focus on getting into shape. Focus on becoming the kind of person who never misses a workout.", category: C.HEALTH },
  { text: "If you are the smartest person in the room, you are in the wrong room. Hang out with, and learn from people smarter than yourself. Even better, find smart people who will disagree with you.", category: C.LEARN },
  { text: "You should demand extraordinary evidence in order to believe extraordinary claims.", category: C.LEARN },
  { text: "Rule of 3 in conversation: To get to the real reason, ask a person to go deeper than what they just said. Then again, and then once more. The third time’s answer is the one closest to the truth.", category: C.RELATIONS },
  { text: "Pros make as many mistakes as amateurs; they’ve just learned how to gracefully recover from their mistakes.", category: C.WORK },
  { text: "Don’t be the best. Be the only.", category: C.WORK },
  { text: "Everyone is shy. Other people are waiting for you to introduce yourself to them; they are waiting for you to send them an email; they are waiting for you to ask them on a date. Go ahead.", category: C.RELATIONS },
  { text: "The more you are interested in others the more interesting they’ll find you. To be interesting, be interested.", category: C.RELATIONS },
  { text: "Don’t take it personally when someone turns you down. Assume they are like you: busy, occupied, distracted. Try again later. It’s amazing how often a second try works.", category: C.RELATIONS },
  { text: "The purpose of a habit is to remove that action from self-negotiation. You no longer expend energy deciding whether to do it. You just do it. Good habits can range from telling the truth to flossing.", category: C.HEALTH },
  { text: "Promptness is a sign of respect.", category: C.RELATIONS },
  { text: "When you are young, spend at least 6 months to 1 year living as cheaply as you can owning as little as you possibly can eating beans and rice in a tiny room or tent. That way any time you have to risk something in the future, you won’t be afraid of the “worst-case” scenario.", category: C.WISDOM },
  { text: "Trust me: There is no “them.”", category: C.WISDOM },
  { text: "Tend to the small things. More people are defeated by blisters than by mountains.", category: C.WISDOM },
  { text: "You lead by letting others know what you expect of them which may exceed what they themselves expect. Provide them a reputation that they can step up to.", category: C.WORK },
  { text: "If you ask for someone’s feedback you’ll get a critic. But if instead you ask for advice you’ll get a partner.", category: C.WORK },
  { text: "The Golden Rule will never fail you. It is the foundation of all other virtues.", category: C.WISDOM },
  { text: "To make something good, just do it. To make something great, just redo it redo it, redo it. The secret to making fine things is in remaking them.", category: C.CREATIVITY },
  { text: "This is true: It’s hard to cheat an honest person.", category: C.WISDOM },
  { text: "Expand your mind by thinking with your feet on a walk or with your hand in a notebook. Think outside your brain.", category: C.CREATIVITY },
  { text: "At first, buy the absolute cheapest tools you can find. Upgrade the ones you use a lot. If you wind up using some tool for a job buy the very best you can afford.", category: C.PRACTICAL },
  { text: "Shorten your to-do list by asking yourself “What is the worst that will happen if this does not get done?” Eliminate all but the disasters.", category: C.WORK },
  { text: "To move through a place you may not be permitted, act like you belong there.", category: C.PRACTICAL },
  { text: "Nothing elevates a person higher than taking responsibility for their mistakes. If you mess up, fess up. It’s astounding how powerful this ownership is.", category: C.WISDOM },
  { text: "Hatred is a curse that does not affect the hated. It only poisons the hater. Release a grudge as if it were a poison.", category: C.WISDOM },
  { text: "Don’t take a job because it pays the most money.", category: C.WORK },
  { text: "You can obsess about your customers or you can obsess about beating the competition. Both work, but of the two obsessing about your customers will take you further.", category: C.WORK },
  { text: "“No” is an acceptable answer even without a reason.", category: C.WISDOM },
  { text: "Separate the processes of creating from improving. You can’t write and edit or sculpt and polish or make and analyze at the same time. If you do, the editor stops the creator. While you invent, don’t select. While you sketch, don’t inspect. While you write the first draft, don’t reflect. At the start, the creator mind must be unleashed from judgment.", category: C.CREATIVITY },
  { text: "If you are not falling down occasionally you are just coasting.", category: C.WISDOM },
  { text: "Perhaps the most counterintuitive truth of the universe is that the more you give to others the more you’ll get. Understanding this is the beginning of wisdom.", category: C.WISDOM },
  { text: "Keep showing up. 99% of success is just showing up. In fact, most success is just persistence.", category: C.WORK },
  { text: "Friends are better than money. Almost anything money can do friends can do better. In so many ways, a friend with a boat is better than owning a boat.", category: C.RELATIONS },
  { text: "When an object is lost, 95% of the time it is hiding within arm’s reach of where it was last seen. Search in all possible locations in that radius and you’ll find it.", category: C.PRACTICAL },
  { text: "A vacation + a disaster = an adventure.", category: C.TRAVEL },
  { text: "Don’t be in haste. When you are in a hurry you are more easily conned or manipulated.", category: C.WISDOM },
  { text: "Forgiveness is accepting the apology you will never get.", category: C.WISDOM },
  { text: "To cultivate a habit switch your language from “I can or can’t do” to “I do or don’t do.” You shift the weight from a wavering choice to an unwavering identity.", category: C.HEALTH },
  { text: "Be more generous than necessary. No one on their deathbed has ever regretted giving too much away. There is no point to being the richest person in the cemetery.", category: C.MONEY },
  { text: "You need teachers, parents customers, fans, and friends because they will see who you are becoming before you will.", category: C.RELATIONS },
  { text: "There is no limit on how much we can improve what we start with. There is no limit on better.", category: C.WORK },
  { text: "Be prepared: When you have 90% of a large project completed finishing the final details will take another 90%. Houses and films are famous for having two 90%s.", category: C.WORK },
  { text: "Before you are old attend as many funerals as you can bear and listen. Nobody talks about the departed’s achievements. The only thing people will remember is what kind of person you were while you were achieving.", category: C.WISDOM },
  { text: "Anything real begins with the fiction of what could be. Imagination is therefore the most potent force in the universe. And you can get better at it. It’s the one skill in life that benefits from ignoring what everyone else knows.", category: C.CREATIVITY },
  { text: "When crises strike don’t waste them. No problems, no progress.", category: C.WISDOM },
  { text: "You really don’t want to be famous. Read the biography of any famous person.", category: C.WISDOM },
  { text: "On vacation go to the most remote place on your itinerary first bypassing the cities and then return to the big city at the end. You’ll maximize the shock of otherness in the remote, and then later you’ll welcome the familiar conveniences of a busy city on the way back.", category: C.TRAVEL },
  { text: "When you get invited to do something in the future ask yourself: Would I do this tomorrow? Not too many promises will pass that immediacy filter.", category: C.WISDOM },
  { text: "Don’t say anything about someone in email you would not be comfortable saying to them directly because eventually it will reach them.", category: C.WISDOM },
  { text: "If you ask to be hired mainly because you need a job you are just another problem for the boss; if you can solve many of the problems the boss has right now you are hired. To be hired, think like your boss.", category: C.WORK },
  { text: "It is not a compliment if it comes with a request.", category: C.RELATIONS },
  { text: "Art is in what you leave out.", category: C.CREATIVITY },
  { text: "Acquiring things will rarely bring you deep satisfaction. But acquiring experiences will.", category: C.MONEY },
  { text: "You are what you do. Not what you say not what you believe not how you vote but what you spend your time on.", category: C.WISDOM },
  { text: "Rule of 7 in research: You can find out anything if you are willing to go seven levels. If the first source you ask doesn’t know ask them who you should ask next and so on down the line. If you are willing to go to the seventh source you’ll almost always get your answer.", category: C.LEARN },
  { text: "To earn bliss just for a moment send someone you don’t know a compliment for something they did.", category: C.RELATIONS },
  { text: "When someone is nasty, hateful, or mean toward you treat their behavior like an affliction or illness they have. That makes it easier to have empathy toward them which can soften the conflict.", category: C.RELATIONS },
  { text: "Eliminating clutter makes room for your true treasures.", category: C.PRACTICAL },
  { text: "Don’t ever respond to a solicitation or a proposal on the phone. The urgency is a disguise for a scam.", category: C.PRACTICAL },
  { text: "Experience is overrated. Most breakthrough accomplishments were done by people doing them for the first time. Therefore when hiring hire for aptitude and attitude and then train for skills.", category: C.WORK },
  { text: "How to apologize: quickly, specifically, sincerely. Don’t ruin an apology with an excuse.", category: C.RELATIONS },
  { text: "Don’t bother asking a barber if you need a haircut. Pay attention to incentives.", category: C.WISDOM },
  { text: "That thing that made you weird as a kid could make you great as an adult —if you don’t lose it.", category: C.WISDOM },
  { text: "Following your bliss is a recipe for paralysis if you don’t know what you are passionate about. A better path for most youth is “master something.” Through mastery of one thing you’ll command a viewpoint to steadily find where your bliss is.", category: C.WORK },
  { text: "To quiet a crowd or a drunk, just whisper.", category: C.PRACTICAL },
  { text: "When you lend something pretend you are gifting. If it is returned you’ll be surprised and happy.", category: C.RELATIONS },
  { text: "You are never too young to wonder “Why am I still doing this?” You need to have an excellent answer.", category: C.WISDOM },
  { text: "A balcony or porch needs to be at least 6 feet (2 meters) deep or it won’t be used.", category: C.PRACTICAL },
  { text: "Life gets better as you replace transactions with relationships.", category: C.RELATIONS },
  { text: "Investing small amounts of money over a long time works miracles but no one wants to get rich slow.", category: C.MONEY },
  { text: "The main thing is to keep the main thing the main thing.", category: C.WISDOM },
  { text: "When in doubt, overtip.", category: C.MONEY },
  { text: "To build strong children reinforce their sense of belonging to a family by articulating exactly what is distinctive about your family. They should be able to say with pride “Our family does X.”", category: C.FAMILY },
  { text: "If you are not embarrassed by your past self you have probably not grown up yet.", category: C.WISDOM },
  { text: "Outlaw the word “you” during domestic arguments.", category: C.FAMILY },
  { text: "If you have any doubt at all about being able to carry a load in one trip do yourself a huge favor and make two trips.", category: C.PRACTICAL },
  { text: "Over the long term the future is decided by optimists. To be an optimist you don’t have to ignore the multitude of problems we create; you just have to imagine how much our ability to solve problems improves.", category: C.WISDOM },
  { text: "Don’t let someone else’s urgency become your emergency. In fact, don’t be governed by the urgent of any sort. Focus on the important. The urgent is a tyrant. The important should be your king. Down with the tyranny of the urgent!", category: C.WORK },
  { text: "Learn how to take a 20-minute power nap without embarrassment.", category: C.HEALTH },
  { text: "Paradoxically, the worst evils in the world are committed by those who truly believe they are combating evil. Be extremely vigilant with yourself when facing evil.", category: C.WISDOM },
  { text: "Don’t reserve your kindest praise for a person until their eulogy. Tell them while they are alive when it makes a difference to them. Write it in a letter they can keep.", category: C.RELATIONS },
  { text: "Fear is fueled by a lack of imagination. The antidote to fear is not bravery; it looks more like imagination.", category: C.WISDOM },
  { text: "Train employees well enough that they could get another job but treat them well enough that they never want to.", category: C.WORK },
  { text: "If it fails where you thought it would fail that is not a failure.", category: C.WORK },
  { text: "Superheroes and saints never make art. Only imperfect beings can make art because art begins in what is broken.", category: C.CREATIVITY },
  { text: "If someone is trying to convince you it’s not a pyramid scheme it’s a pyramid scheme.", category: C.PRACTICAL },
  { text: "Don’t create things to make money; make money so you can create things. The reward for good work is more work.", category: C.WORK },
  { text: "Leave a gate behind you the way you first found it.", category: C.PRACTICAL },
  { text: "In 100 years a lot of what we take to be true now will be proved to be wrong, maybe even embarrassingly wrong. A good question to ask yourself today is “What might I be wrong about?” This is the only worry worth having.", category: C.WISDOM },
  { text: "Learn how to tie a bowline knot. Practice in the dark. With one hand. For the rest of your life you’ll use this knot more times than you would ever believe.", category: C.PRACTICAL },
  { text: "The greatest rewards come from working on something that nobody has words for. If you possibly can work where there are no names for what you do.", category: C.WORK },
  { text: "On the way to a grand goal celebrate the smallest victories as if each one were the final goal. That way, no matter where it ends you are victorious.", category: C.WISDOM },
  { text: "In all things—except love—start with the exit strategy. Prepare for the ending. Almost anything is easier to get into than out of.", category: C.WISDOM },
  { text: "Don’t aim to have others like you; aim to have them respect you.", category: C.RELATIONS },
  { text: "The foundation of maturity: Just because it’s not your fault doesn’t mean it’s not your responsibility.", category: C.WISDOM },
  { text: "A multitude of bad ideas is necessary for one good idea.", category: C.CREATIVITY },
  { text: "The hard part in predicting the future is to forget everything you expect it to be.", category: C.WISDOM },
  { text: "Compliment people behind their back. It’ll come back to you.", category: C.RELATIONS },
  { text: "Most overnight successes —in fact, any significant successes— take at least 5 years. Budget your life accordingly.", category: C.WORK },
  { text: "The job of a grandparent is to grandparent, not to parent. Parent’s house, parent rules. Grandparent’s house, grandparent rules.", category: C.FAMILY },
  { text: "You don’t need more time because you already have all the time that you will ever get; you need more focus.", category: C.WORK },
  { text: "The foolish person winds up doing at the end what the smart person does at the beginning.", category: C.WISDOM },
  { text: "For marital bliss take turns allowing each partner to be always right.", category: C.RELATIONS },
  { text: "If the cost of something is not advertised it is a sign that it’s more than you can afford.", category: C.MONEY },
  { text: "Everyone’s time is finite and shrinking. The highest leverage you can get with your money is to buy someone else’s time. Hire and outsource when you can.", category: C.MONEY },
  { text: "Your best response to an insult is “You’re probably right.” Often they are.", category: C.WISDOM },
  { text: "Assume anyone asking for your account information for any reason is guilty of scamming you unless proven innocent. You must control the channel.", category: C.PRACTICAL },
  { text: "Fear makes people do stupid things so don’t trust anything made in fear.", category: C.WISDOM },
  { text: "Be strict with yourself, forgiving of others. The reverse is hell for everyone.", category: C.WISDOM },
  { text: "If you can avoid seeking the approval of others your power is limitless.", category: C.WISDOM },
  { text: "Your passions should fit you exactly but your purpose in life should exceed you. Work for something much larger than yourself.", category: C.WISDOM },
  { text: "When a child asks an endless string of “Why?” questions, the smartest reply is “I don’t know, what do you think?”", category: C.FAMILY },
  { text: "Recipe for success: underpromise and overdeliver.", category: C.WORK },
  { text: "Show me your calendar and I will tell you your priorities. Tell me who your friends are and I’ll tell you where you’re going.", category: C.WISDOM },
  { text: "When brainstorming improvising jamming with others you’ll go much further and deeper if you build upon each contribution with a playful “yes—and” example instead of a deflating “no—but” reply.", category: C.CREATIVITY },
  { text: "Work to become, not to acquire.", category: C.WISDOM },
  { text: "Contemplating the weaknesses of others is easy; contemplating the weaknesses in yourself is hard but it pays a much higher reward.", category: C.WISDOM },
  { text: "When you are young have friends who are older; when you are old have friends who are younger.", category: C.RELATIONS },
  { text: "You will complete your mission in life when you figure out what your mission in life is. Your purpose is to discover your purpose. This is not a paradox. This is the way.", category: C.WISDOM },
  { text: "With sharp things always cut away from yourself.", category: C.PRACTICAL },
  { text: "Calm is contagious. Be calm to help others.", category: C.WISDOM },
  { text: "When someone tells you something is wrong, they’re usually right. When they tell you how to fix it they’re usually wrong.", category: C.WORK },
  { text: "You are only as young as the last time you changed your mind.", category: C.WISDOM },
  { text: "When hitchhiking look like the person you want to pick you up.", category: C.TRAVEL },
  { text: "Worth repeating: Measure twice, cut once.", category: C.PRACTICAL },
  { text: "Money is overrated. Truly new things rarely need an abundance of money. Almost all breakthroughs are made by those who lack money. Passion, persistence, belief, and ingenuity are required to invent new things — qualities the poor and young often have in abundance. Stay hungry.", category: C.MONEY },
  { text: "If you can’t tell what you desperately need it’s probably sleep.", category: C.HEALTH },
  { text: "Ignore what others may be thinking of you because they aren’t thinking of you.", category: C.WISDOM },
  { text: "Writing down one thing you are grateful for each day is the cheapest possible therapy ever.", category: C.HEALTH },
  { text: "If you meet a jerk, ignore them. If you meet jerks everywhere every day look deeper into yourself.", category: C.RELATIONS },
  { text: "It is much easier to change how you think by changing your behavior than it is to change your behavior by changing how you think. Act out the change you seek.", category: C.WISDOM },
  { text: "If you think you saw a mouse, you did. And if there is one, there are more.", category: C.PRACTICAL },
  { text: "Don’t worry how or where you begin. As long as you keep moving, your success will arrive far from where you start.", category: C.WISDOM },
  { text: "Avoid hitting the snooze button. That’s just training you to oversleep.", category: C.HEALTH },
  { text: "You’ll learn a lot more if you ask people “how are you sleeping?” instead of “how are you doing?”", category: C.RELATIONS },
  { text: "Generally, say less than necessary.", category: C.RELATIONS },
  { text: "Each time you connect to people bring them a blessing; then they’ll be happy to see you when you bring them a problem.", category: C.RELATIONS },
  { text: "Even in the tropics it gets colder at night than you think. Pack warmly.", category: C.TRAVEL },
  { text: "The work on any worthy project is endless, infinite. You cannot limit the work so you must limit your hours. Your time, not the work is the only thing you can manage.", category: C.WORK },
  { text: "You can reduce the annoyance of someone’s stupid belief by increasing your understanding of why they believe it.", category: C.WISDOM },
  { text: "This is the best time ever to make something. None of the greatest, coolest creations 20 years from now have been invented yet. You are not late.", category: C.CREATIVITY },
  { text: "To transcend the influence of your heroes copy them shamelessly like a student until you get them out of your system. That is the way of all masters.", category: C.CREATIVITY },
  { text: "Things do not need to be perfect to be wonderful. Especially weddings.", category: C.WISDOM },
  { text: "When you are stuck, sleep on it. Give your subconscious an assignment while you sleep. You’ll have an answer in the morning.", category: C.CREATIVITY },
  { text: "All the greatest prizes in life in wealth, relationships, or knowledge come from the magic of compounding interest by amplifying small steady gains. All you need for abundance is to keep adding 1% more than you subtract on a regular basis.", category: C.WISDOM },
  { text: "You can eat any dessert you want if you take only three bites.", category: C.HEALTH },
  { text: "Don’t treat people as bad as they are. Treat them as good as you are.", category: C.RELATIONS },
  { text: "Children totally accept —and crave—family rules. “In our family we have a rule for X” is the only excuse a parent needs for setting a family policy.", category: C.FAMILY },
  { text: "When you confront a stuck bolt or screw: righty tighty, lefty loosey.", category: C.PRACTICAL },
  { text: "Bad things can happen fast but almost all good things happen slowly.", category: C.WISDOM },
  { text: "We are not a body that carries a soul. We are a soul that is assigned a body not of our choosing, but in our care.", category: C.WISDOM },
  { text: "If your goal does not have a schedule, it is a dream.", category: C.WORK },
  { text: "Be a good ancestor. Do something a future generation will thank you for. A simple thing is to plant a tree.", category: C.WISDOM },
  { text: "People can’t remember more than three points from a speech.", category: C.WORK },
  { text: "The greatest breakthroughs are missed because they look like really hard work.", category: C.WORK },
  { text: "To be remarkable, read books.", category: C.LEARN },
  { text: "Finite games are played to win or lose. Infinite games are played to keep the game going. Seek out infinite games because they yield unlimited rewards.", category: C.WISDOM },
  { text: "To succeed, get other people to pay you; to become wealthy, help other people to succeed.", category: C.MONEY },
  { text: "Your behavior, not your opinions will change the world.", category: C.WISDOM },
  { text: "A problem that can easily be solved with money is not really a problem because its solution is obvious. Focus on problems with non-obvious solutions.", category: C.WORK },
  { text: "Every person you meet knows an amazing lot about something you know virtually nothing about. It won’t be obvious and your job is to discover what it is.", category: C.RELATIONS },
  { text: "Cultivate an allergy to average.", category: C.WORK },
  { text: "To combat an adversary become their friend.", category: C.RELATIONS },
  { text: "If you are buying stock, the person selling it thinks it is worth less than you do. If you are selling, they think it is worth more than you do. Each time you are ready to buy or sell stock ask yourself “What do I know that they don’t?”", category: C.MONEY },
  { text: "You don’t marry a person you marry a family.", category: C.FAMILY },
  { text: "Be nice to your children because they are going to choose your nursing home.", category: C.FAMILY },
  { text: "About 99% of the time the right time is right now.", category: C.WISDOM },
  { text: "All guns are loaded.", category: C.PRACTICAL },
  { text: "Cultivate 12 people who love you because they are worth more than 12 million people who like you.", category: C.RELATIONS },
  { text: "Always be quick to give credit and to take blame.", category: C.WORK },
  { text: "Be frugal in all things except in your passions. Select a few interests that you gleefully splurge on. In fact, be all-around thrifty so that you can splurge on your passions.", category: C.MONEY },
  { text: "To manage yourself use your head; to manage others use your heart.", category: C.WORK },
  { text: "Dance with your hips.", category: C.HEALTH },
  { text: "Don’t let your email inbox become your to-do list run by others.", category: C.WORK },
  { text: "The best way to untangle a knotty tangle is not to “untie” the knots but to keep pulling the loops apart wider and wider. Just make the mess as big, loose, and open as possible. As you open up the knots, they will unravel themselves.", category: C.PRACTICAL },
  { text: "Take one simple thing —almost anything— but take it extremely seriously as if it is the only thing in the world —or maybe the entire world is in it— and by taking it seriously you’ll light up the sky.", category: C.CREATIVITY },
  { text: "When making something always get a few extras—extra material extra parts, extra space, extra finishes. The extras serve as backups for mistakes reduce stress and fill your inventory for the future. They are the cheapest insurance.", category: C.PRACTICAL },
  { text: "No one is as impressed with your possessions as you are.", category: C.WISDOM },
  { text: "Don’t ever work for someone you don’t want to become.", category: C.WORK },
  { text: "No secrets. You are much better off delivering unwelcome news to someone yourself directly. A secret is rarely unknown, which means inevitably someone else will share it. Meanwhile, the secret corrodes all who hold it. Resist accepting secrets.", category: C.RELATIONS },
  { text: "The expanding universe is overflowing with abundance. It is so full that improvement can often be gained only by subtracting. Keep removing, until you can’t. End with wanting more, not less.", category: C.CREATIVITY },
  { text: "Figure out what time of day you are most productive and protect that time period.", category: C.WORK },
  { text: "Experiences are fun and having influence is rewarding but only mattering makes us happy. Do stuff that matters.", category: C.WISDOM },
  { text: "Greatness is incompatible with optimizing in the short term. To achieve greatness requires a long view. Raise your time horizon to raise your goal.", category: C.WORK },
  { text: "Most wonderful things quickly become unwonderful if they are repeated too often. Once-in-a-life is often the optimal interval.", category: C.WISDOM },
  { text: "You have to first follow the rules with diligence in order to break them productively.", category: C.CREATIVITY },
  { text: "If you stop to listen to a musician or street performer for more than a minute you owe them a dollar.", category: C.RELATIONS },
  { text: "Learning probability and statistics is far more useful than learning algebra and calculus.", category: C.LEARN },
  { text: "If winning becomes too important in a game change the rules to make it more fun. Changing rules can become the new game.", category: C.WISDOM },
  { text: "The greatest teacher is called “doing.”", category: C.LEARN },
  { text: "Anything you say before the word “but” does not count.", category: C.RELATIONS },
  { text: "Courtesy costs nothing. When you borrow something, return it cleaned. Lower the toilet seat after use. Let the car in front of you merge. Return shopping carts to their designated areas. Let the people in the elevator exit before you enter. These courtesies are free.", category: C.WISDOM },
  { text: "Whenever there is an argument between two sides find the third side.", category: C.WISDOM },
  { text: "The consistency of your endeavors (exercise, companionship, work) is more important than the quantity. Nothing beats small things done every day which is way more important than what you do occasionally.", category: C.HEALTH },
  { text: "When you lead your real job is to create more leaders not more followers.", category: C.WORK },
  { text: "It is the duty of a teacher to get everything out of a student and the duty of a student to get everything out of a teacher.", category: C.LEARN },
  { text: "Efficiency is highly overrated; goofing off is highly underrated. Regularly scheduled sabbaths, sabbaticals vacations, breaks, aimless walks and time off are essential for top performance of any kind. The best work ethic requires a good rest ethic.", category: C.HEALTH },
  { text: "Speak confidently as if you are right but listen carefully as if you are wrong.", category: C.WISDOM },
  { text: "Productivity is often a distraction. Don’t aim for better ways to get through your tasks as quickly as possible. Instead aim for better tasks that you never want to stop doing.", category: C.WORK },
  { text: "Your enjoyment of travel is inversely proportional to the size of your luggage. This is 100% true of backpacking. It is liberating to realize how little you really need.", category: C.TRAVEL },
  { text: "Ask funders for money and they’ll give you advice; but ask for advice and they’ll give you money.", category: C.MONEY },
  { text: "The biggest lie we tell ourselves is “I don’t need to write this down because I will remember it.”", category: C.PRACTICAL },
  { text: "Criticize in private, praise in public.", category: C.WORK },
  { text: "Don’t keep making the same mistakes; try to make new mistakes.", category: C.WISDOM },
  { text: "Your growth as a mature being is measured by the number of uncomfortable conversations you are willing to have.", category: C.WISDOM },
  { text: "Handy measure: The distance between the fingertips of your outstretched arms at shoulder level is roughly your height.", category: C.PRACTICAL },
  { text: "Don’t buy anything late at night. There is nothing you need to buy that cannot wait till tomorrow morning.", category: C.MONEY },
  { text: "When you have good news and bad news, give the bad news first because we remember how things end more than how they begin. So elevate the ending with good news.", category: C.RELATIONS },
  { text: "Immediately pay what you owe to vendors, workers, contractors. If you do, they will go out of their way to work with you first next time.", category: C.WORK },
  { text: "The four most powerful words in any negotiation should be uttered by you: “Can you do better?”", category: C.WORK },
  { text: "Three things you need: the ability to not give up something till it works, the ability to give up something that does not work, and the trust in other people to help you distinguish between the two.", category: C.WISDOM },
  { text: "You can find no better medicine for your family than regular meals together without screens.", category: C.FAMILY },
  { text: "There is no such thing as being “on time.” Either you are late or you are early. Your choice.", category: C.WORK },
  { text: "Making art is not selfish; it’s for the rest of us. If you don’t do your thing you are cheating us.", category: C.CREATIVITY },
  { text: "In a genuine survival situation, you can go 3 weeks without food and 3 days without water but only 3 hours without warmth or shade. So don’t worry about food. Focus on temperature and water.", category: C.PRACTICAL },
  { text: "When you are in the wrong be quick to chastise yourself more severely than the aggrieved might. Paradoxically, this can soften their ire.", category: C.RELATIONS },
  { text: "Learn how to be alone without being lonely. Solitude is essential for creativity.", category: C.CREATIVITY },
  { text: "When you feel like quitting just do five more: 5 more minutes, 5 more pages 5 more steps. Then repeat. Tell yourself that you will quit tomorrow but not today.", category: C.WORK },
  { text: "Never ask someone if they are pregnant. Let them tell you.", category: C.RELATIONS },
  { text: "What you do on your bad days matters more than what you do on your good days.", category: C.WISDOM },
  { text: "Ask anyone you admire: Their lucky breaks happened on a detour from their main goal. So embrace detours. Life is not a straight line for anyone.", category: C.WISDOM },
  { text: "To be rich you don’t need to make more money; you chiefly need to better manage the money already flowing through your hands.", category: C.MONEY },
  { text: "When speaking to an audience pause frequently. Pause before you say something in a new way pause after you have said something you believe is important and pause as a relief to let listeners absorb details.", category: C.WORK },
  { text: "The best way to get a correct answer on the internet is to post an obviously wrong answer and wait for someone to correct you.", category: C.PRACTICAL },
  { text: "You’ll get 10 times better results by elevating good behavior rather than punishing bad behavior especially in children and animals.", category: C.FAMILY },
  { text: "Spend as much time crafting the subject line of an email as the message itself because the subject line is often the only thing people read.", category: C.WORK },
  { text: "Don’t wait for the storm to pass; dance in the rain.", category: C.WISDOM },
  { text: "Make stuff that is good for people to have.", category: C.WORK },
  { text: "Keep all your things visible in a hotel room, not in drawers and all gathered into one spot. That way you’ll never leave anything behind.", category: C.TRAVEL },
  { text: "Denying or deflecting a compliment is rude. Accept it with thanks even if you believe it is not deserved.", category: C.RELATIONS },
  { text: "Always read the plaque next to the monument.", category: C.LEARN },
  { text: "When you have some success, the feeling of being an imposter can be real. But when you create things that only you with your unique talents and experience can do then you are absolutely not an imposter. You are the ordained.", category: C.WORK },
  { text: "When you don’t know how much to pay someone for a particular task ask them, “What would be fair?” and their answer usually is.", category: C.MONEY },
  { text: "The general strategy for real estate is to buy the worst property on the best street.", category: C.MONEY },
  { text: "You cannot get smart people to work extremely hard just for money.", category: C.WORK },
  { text: "Half the skill of being educated is learning what you can ignore.", category: C.LEARN },
  { text: "If you’re doing something that you are hiding from others it’s probably not good for you.", category: C.WISDOM },
  { text: "When you need to cut something extremely exact don’t try to do it with one cut. Instead, cut it a bit bigger and then keep trimming it bit by bit until perfect. Professional makers call this “creeping up” to the precise measurement.", category: C.PRACTICAL },
  { text: "Make others feel they are important; it will make their day and it will make your day.", category: C.RELATIONS },
  { text: "Constantly search for overlapping areas of agreement and dwell there. Disagreements will appear to be edge cases.", category: C.RELATIONS },
  { text: "90% of everything is crap. If you think you don’t like something, keep trying to see if you can find the 10% that is not crap.", category: C.WISDOM },
  { text: "You will be judged on how well you treat those who can do nothing for you.", category: C.WISDOM },
  { text: "We tend to overestimate what we can do in a day and underestimate what we can achieve in a decade. Miraculous things can be accomplished if you give it 10 years.", category: C.WORK },
  { text: "Let someone know you remembered their name and they won’t ever forget yours. To help remember their name repeat it on first hearing.", category: C.RELATIONS },
  { text: "Your best job will be one that you were unqualified for because it stretches you. In fact, only apply to jobs you are unqualified for.", category: C.WORK },
  { text: "You can be whatever you want to be so be the person who ends meetings early.", category: C.WORK },
  { text: "Buy used books. They have the same words as the new ones. Also, libraries.", category: C.MONEY },
  { text: "Before you speak, let your words pass through three gates. At the first gate, ask yourself, “Is it true?” At the second gate ask, “Is it necessary?” At the third gate ask, “Is it kind?”", category: C.WISDOM },
  { text: "The only productive way to answer “What should I do now?” is to first tackle the question of “Who should I become?”", category: C.WISDOM },
  { text: "When you board an airplane, arrive at your room in a hotel, or start a new job, locate the emergency exits. It only takes a minute.", category: C.PRACTICAL },
  { text: "The best investing advice: Average returns, maintained for above-average periods of time will yield extraordinary results. Buy and hold.", category: C.MONEY },
  { text: "Take the stairs.", category: C.HEALTH },
  { text: "What you actually pay for something can be twice the listed price because the energy, time, and money needed to set it up, learn, maintain, repair it and then dispose of it when done all have their own cost. Not all prices appear on labels.", category: C.MONEY },
  { text: "If a young student is struggling first thing: Check their eyesight.", category: C.FAMILY },
  { text: "It’s thrilling to be extremely polite to rude strangers.", category: C.WISDOM },
  { text: "Most articles and stories are improved significantly if you delete the first page of the manuscript. Start with the action.", category: C.CREATIVITY },
  { text: "Getting cheated occasionally is the small price for trusting the best of everyone because when you trust the best in others they generally treat you best.", category: C.WISDOM },
  { text: "It’s possible that a not-so-smart person who can communicate well can do much better than a super-smart person who can’t communicate well. It is much easier to improve your communication skills than your intelligence.", category: C.WORK },
  { text: "Take note if you find yourself wondering “Where is my good knife?” That means you have bad ones. Get rid of those.", category: C.PRACTICAL },
  { text: "For the best results with your children spend only half the money you think you should but double the time with them.", category: C.FAMILY },
  { text: "Avoid wearing a hat that has more character than you do.", category: C.WISDOM },
  { text: "Looking ahead, focus on direction rather than destinations. Maintain the right direction and you’ll arrive at where you want to go.", category: C.WISDOM },
  { text: "Art is whatever you can get away with.", category: C.CREATIVITY },
  { text: "Purchase the most recent tourist guidebook to your hometown or region. You’ll learn a lot by playing the tourist once a year.", category: C.TRAVEL },
  { text: "To become a hero, thank a teacher who made a difference in your life.", category: C.RELATIONS },
  { text: "When buying a garden hose, an extension cord, or a ladder, get one substantially longer than you think you need. It’ll be the right size.", category: C.PRACTICAL },
  { text: "When you are stuck explain your problem to others. Often simply laying out a problem will present a solution. Make “explaining the problem” part of your troubleshooting process.", category: C.WORK },
  { text: "Don’t wait in line to eat something famous. It is rarely worth the wait.", category: C.TRAVEL },
  { text: "When introduced to someone make eye contact and count to four or say to yourself, “I see you.” You’ll both remember each other.", category: C.RELATIONS },
  { text: "Your group can achieve great things way beyond your means simply by showing people that they are appreciated.", category: C.WORK },
  { text: "Be a pro. Back up your backup. Have at least one physical backup and one backup in the cloud. Backups are cheap compared to regrets.", category: C.PRACTICAL },
  { text: "Prescription for popular success: do something strange. Make a habit of your weird.", category: C.CREATIVITY },
  { text: "Your time and space are limited. Remove, give away, throw out anything that no longer gives you joy in order to make room for those that do.", category: C.WISDOM },
  { text: "To signal an emergency use the rule of 3: 3 shouts, 3 horn blasts, or 3 whistles.", category: C.PRACTICAL },
  { text: "Don’t compare your inside to someone else’s outside.", category: C.WISDOM },
  { text: "The ideal balance for exploring new things vs. optimizing those already found is ⅓. Spend ⅓ of your time on exploring and ⅔ on optimizing and deepening.", category: C.WISDOM },
  { text: "Occasionally your first idea is best, but usually it’s the fifth idea. You need to get all the obvious ideas out of the way. Try to surprise yourself.", category: C.CREATIVITY },
  { text: "Don’t bother fighting the old just build the new.", category: C.WORK },
  { text: "Actual great opportunities will not have “Great Opportunities” in the subject line.", category: C.WORK },
  { text: "When someone tells you about the peak year of human history it will always be the year when they were 10 years old—which is the peak of any human’s existence. Factor that into what they say.", category: C.WISDOM },
  { text: "To rapidly reveal the true character of a person you just met observe them stuck on an abysmally slow internet connection.", category: C.RELATIONS },
  { text: "In preparing for a long hike old shoes of any type are superior to brand-new shoes of any type. Don’t use a long hike to break in shoes.", category: C.TRAVEL },
  { text: "When negotiating don’t aim for a bigger piece of the pie; aim to create a bigger pie.", category: C.WORK },
  { text: "You are as big as the things that make you angry.", category: C.WISDOM },
  { text: "You see only 2% of another person and they see only 2% of you. Attune yourself to the hidden 98%.", category: C.RELATIONS },
  { text: "Our descendants will achieve things that will amaze us yet a portion of what they will create could have been made with today’s materials and tools if we had had the imagination. Think bigger.", category: C.CREATIVITY },
  { text: "Do more of what looks like work to others but is play for you.", category: C.WORK },
  { text: "If you want something to get done ask a busy person to do it.", category: C.WORK },
  { text: "Remember that repair tasks take 3 times longer than expected even when you expect them to take 3 times longer.", category: C.PRACTICAL },
  { text: "Copying others is a good way to start. Copying yourself is a disappointing way to end.", category: C.CREATIVITY },
  { text: "If you repeated what you did today 365 more times will you be where you want to be next year?", category: C.WISDOM },
  { text: "The best time to negotiate your salary for a new job is the moment after they say they want you and not before. It is to your advantage to get them to give a number before you do.", category: C.WORK },
  { text: "Pay attention to what you pay attention to.", category: C.WISDOM },
  { text: "For maximum results focus on your biggest opportunities not your biggest problems.", category: C.WORK },
  { text: "Every breakthrough is at first laughable and ridiculous. In fact, if it did not start out laughable and ridiculous it is not a breakthrough.", category: C.CREATIVITY },
  { text: "Reading to your children regularly is the best school they will ever get.", category: C.FAMILY },
  { text: "If you don’t smoke before the age of 25 you are unlikely to ever start; if you do smoke before 25 you are unlikely to ever quit.", category: C.HEALTH },
  { text: "It doesn’t matter how many people don’t appreciate you or your work. The only thing that counts is how many do.", category: C.WORK },
  { text: "It is far safer after a car accident to remain in the car rather than standing near it on the road where the accident increases the chances of another accident.", category: C.PRACTICAL },
  { text: "When you are looking for a job, remember that somewhere an employer is desperately hunting for someone like you especially if you are unconventional. Your real job is to make that match happen.", category: C.WORK },
  { text: "Rather than steering your life to avoid the unexpected aim directly for it.", category: C.WISDOM },
  { text: "Don’t grocery shop while hungry.", category: C.HEALTH },
  { text: "If your opinions on one subject can be predicted from your opinions on another you may be in the grip of an ideology. When you truly think for yourself your conclusions will not be predictable.", category: C.WISDOM },
  { text: "You can really change someone’s life for the better simply by offering words of encouragement.", category: C.RELATIONS },
  { text: "When you are presented with a task that could be completed in 2 minutes or less do it immediately.", category: C.WORK },
  { text: "The stronger your beliefs, the stronger your reasons to question them regularly. Don’t simply believe everything you think you believe.", category: C.WISDOM },
  { text: "When a customer of yours complains always apologize first and ask “What can we do to resolve this?” even if it is not your fault.", category: C.WORK },
  { text: "If you loan someone $20 and you never see them again because they are avoiding paying you back that makes it worth $20.", category: C.MONEY },
  { text: "A superpower worth cultivating is learning from people you don’t like. It is called “humility.” Despite their character flaws they each know something you don’t.", category: C.LEARN },
  { text: "Don’t purchase extra insurance if you are renting a car with a credit card.", category: C.MONEY },
  { text: "For every good thing you love ask yourself what your proper dose is.", category: C.HEALTH },
  { text: "Hikers’ rule: Don’t step on what you can step over; don’t step over what you can walk around.", category: C.TRAVEL },
  { text: "The trick to making wise decisions is to evaluate your choices as if you were looking back 25 years from today. What would your future self think?", category: C.WISDOM },
  { text: "To be interesting just tell your own story with uncommon honesty.", category: C.RELATIONS },
  { text: "When speaking to an audience it’s better to fix your gaze on a few people than to “spray” your gaze across the room. Your eyes telegraph to others whether you really believe what you are saying.", category: C.WORK },
  { text: "The main reason to produce something every day is that you must throw away a lot of good work to reach the great stuff. To let it all go easily you need to be convinced that there is “more where that came from.”", category: C.CREATIVITY },
  { text: "The real test of your character is not how you deal with adversity but how you deal with power. The only cure for power is humility and the admission that your power comes from luck. The superior person knows they are lucky.", category: C.WISDOM },
  { text: "You will thrive more —and so will others— when you promote what you love rather than bash what you hate. Life is short; focus on the good stuff.", category: C.WISDOM },
  { text: "When sharing, one person divides the other chooses.", category: C.PRACTICAL },
  { text: "It is easy to get trapped by your own success. Say no to tasks you probably won’t fail at and say yes to what you could fail at.", category: C.WORK },
  { text: "Unhappiness comes from wanting what others have. Happiness comes from wanting what you already have.", category: C.WISDOM },
  { text: "When working with electricity volts hurt, but amps kill.", category: C.PRACTICAL },
  { text: "To get your message across follow this formula used by ad writers everywhere: simplify, simplify, simplify, then exaggerate.", category: C.CREATIVITY },
  { text: "Pay attention to who you are around when you feel your best. Be with them more often.", category: C.RELATIONS },
  { text: "Assume no one remembers names. As a courtesy reintroduce yourself by name even to those you have previously met.", category: C.RELATIONS },
  { text: "What you do instead of work might become your real work.", category: C.WORK },
  { text: "The very best thing you can do for your kids is to love your spouse.", category: C.FAMILY },
  { text: "Your golden ticket is being able to see things from other people’s point of view. This shift enables heartfelt empathy. It also allows you to persuade others and it is the key to great design.", category: C.RELATIONS },
  { text: "If you think that something “goes without saying,” it is usually best for everyone if you just go ahead and say it.", category: C.RELATIONS },
  { text: "To meditate, sit and pay attention to your breathing. Your mind will wander to thoughts. Then you bring your attention back to your breathing where it can’t think. Wander. Retreat. Keep returning to breath no thoughts. That is all.", category: C.HEALTH },
  { text: "Five years from now you will wish you had started today.", category: C.WISDOM },
  { text: "If we all threw our troubles into a big pile and we saw everyone else’s problems we would immediately grab ours back.", category: C.WISDOM },
  { text: "Your heart needs to be as educated as your mind.", category: C.WISDOM },
  { text: "You can’t change your past but you can change your story about it. What is important is not what happened to you but what you did about what happened to you.", category: C.WISDOM },
  { text: "To have a great trip, head toward an interest rather than to a place. Travel to passions rather than destinations.", category: C.TRAVEL },
  { text: "Let your children choose their punishments. They’ll be tougher than you will.", category: C.FAMILY },
  { text: "In the garden dig a $100 hole for a $10 plant.", category: C.PRACTICAL },
  { text: "Fully embrace “What is the worst that can happen?” at each juncture in life. Rehearsing your response to the “worst” can reveal it as an adventure and rob it of its power to stall you.", category: C.WISDOM },
  { text: "Make one to throw away. The only way to write a great book is to first write an awful book. Ditto for a movie, song, piece of furniture or anything.", category: C.CREATIVITY },
  { text: "For lofty goals, measure your progress from where you started rather than where you need to finish.", category: C.WORK },
  { text: "You increase your chance of successfully removing a clothing stain if you keep it wet while you work on it. It’s much harder once it dries out.", category: C.PRACTICAL },
  { text: "Anger is not the proper response to anger. When you see someone angry you are seeing their pain. Compassion is the proper response to anger.", category: C.RELATIONS },
  { text: "When you find something you really enjoy do it slowly.", category: C.WISDOM },
  { text: "Ignore dogs that bark. Look for the charging dog not barking. That is the one who bites.", category: C.PRACTICAL },
  { text: "Assuming you are average half of the world will be less proficient than you. Many of these people can’t handle forms complex instructions, or tricky situations. Be kind to them because the world is not.", category: C.WISDOM },
  { text: "Your flaws and your strengths are two poles of the same traits. The sole difference is in the goal. To earn dignity with your flaws own up to them, and make sure you push on things that matter.", category: C.WISDOM },
  { text: "The end is almost always the beginning of something better.", category: C.WISDOM },
  { text: "It is impossible for you to become poor by giving. It is impossible for you to become wealthy without giving.", category: C.MONEY },
  { text: "Try hard to solicit constructive criticism early. You want to hear what’s not working as soon as possible. When it is finished you can’t improve it.", category: C.WORK },
  { text: "To get better at speaking watch a recording of yourself speaking. It is shocking and painful but an effective way to improve.", category: C.WORK },
  { text: "Don’t attribute to malice what can be explained by incompetence.", category: C.WISDOM },
  { text: "Worry is ineffective. It is certain that 99% of the stuff you are anxious about won’t happen.", category: C.HEALTH },
  { text: "You can ignore any website with the word “truth” in its URL.", category: C.PRACTICAL },
  { text: "Be extremely stingy in making promises because you must be generous in keeping them.", category: C.WISDOM },
  { text: "Don’t mistake a clear view of the future for a short distance.", category: C.WISDOM },
  { text: "A proper apology consists of conveying the 3 Rs: regret (genuine empathy with the other) responsibility (not blaming someone else) and remedy (your willingness to fix it).", category: C.RELATIONS },
  { text: "The best way to advise young people is to find out what they really want to do and then advise them to do it.", category: C.RELATIONS },
  { text: "It is usually much easier to make big audacious changes than small incremental ones.", category: C.WORK },
  { text: "The big dirty secret is that everyone especially the famous are just making it up as they go along.", category: C.WISDOM },
  { text: "There is no perfection, only progress. Done is much better than perfect.", category: C.WORK },
  { text: "You choose to be lucky by believing that any setbacks are just temporary.", category: C.WISDOM },
  { text: "If nobody else does what you do you won’t need a resume.", category: C.WORK },
  { text: "To lower tensions during a dispute, mirror the other person’s body language.", category: C.RELATIONS },
  { text: "For a great payoff be especially curious about the things you are not interested in.", category: C.LEARN },
  { text: "It is not hard to identify a thief: It is the one who believes that everybody steals.", category: C.WISDOM },
  { text: "We are unconsciously distracted by seeing our reflection. You can alleviate a lot of the fatigue of teleconferencing all day if you turn off your self-view.", category: C.PRACTICAL },
  { text: "Read the books that your favorite authors once read.", category: C.LEARN },
  { text: "When you can’t decide ask yourself, “Which choice will pay off more later than now?” The easy choice pays off right away. The best choice will pay off at the end.", category: C.WISDOM },
  { text: "As long as an idea stays in your head it is perfect. But perfect things are never real. Immediately put an idea down into words or in a sketch, or as a cardboard prototype. Now your idea is much closer to reality because it is imperfect.", category: C.CREATIVITY },
  { text: "Trust the 3-star product reviews because they tell both the good and the bad, which is the real state for most things.", category: C.PRACTICAL },
  { text: "First, always ask for what you want. Works in relationships, business, life.", category: C.WISDOM },
  { text: "Even if you don’t say anything if you listen carefully people will consider you a great conversationalist.", category: C.RELATIONS },
  { text: "Curiosity is fatal to certainty. The more curious you are the less certain you’ll be.", category: C.LEARN },
  { text: "Measure your wealth not by the things you can buy but by the things that no money can buy.", category: C.MONEY },
  { text: "To learn from your mistakes first laugh at your mistakes.", category: C.WISDOM },
  { text: "It’s unfortunate when someone you carefully trained leaves; but it is worse if you don’t train them and they stay.", category: C.WORK },
  { text: "Your opinion on a contentious issue gains power when you can argue the opposite side as well as they can.", category: C.WISDOM },
  { text: "When you keep people waiting they begin to think of all your flaws.", category: C.RELATIONS },
  { text: "Trust is earned in drops and lost in buckets. Unwavering honesty will help seal in trust.", category: C.RELATIONS },
  { text: "An honest friend is someone who wants nothing at all from you.", category: C.RELATIONS },
  { text: "You will spend one third of your life in your bed sleeping, and almost another third in your chair sitting. It’s worth investing in a great bed and fantastic chair.", category: C.HEALTH },
  { text: "The purpose of listening is not to reply, but to hear what is not being said.", category: C.RELATIONS },
  { text: "Don’t spoil a movie you are sure to see by watching the trailer. Only watch trailers for movies you are unsure of, or unlikely to see.", category: C.PRACTICAL },
  { text: "Your best teacher is your last mistake.", category: C.LEARN },
  { text: "On the dashboard of every gasoline car is a symbol of gas pump with a little arrow. The arrow points to the side of the car that accesses your gas tank. Remember this when you borrow or rent a car.", category: C.PRACTICAL },
  { text: "The perfect kind of art to display in your home are odd pieces that a child is unlikely to forget.", category: C.FAMILY },
  { text: "Spending as little as 15 minutes (1% of your day) on improving how you do your thing, is the most powerful way to amplify and advance your thing.", category: C.WORK },
  { text: "Instead of asking your child what they learned today, ask them who they helped today.", category: C.FAMILY },
  { text: "The greatest killer of happiness is comparison. If you must compare, compare yourself to you yesterday.", category: C.WISDOM },
  { text: "Your 20s are the perfect time to do a few things that are unusual, weird, bold, risky, unexplainable, crazy, unprofitable, and look nothing like “success.” For the rest of your life these experiences will serve as your muse.", category: C.WISDOM },
  { text: "Don’t define yourself by your opinions because then you can’t change your mind. Define yourself by your values.", category: C.WISDOM },
  { text: "To succeed once focus on the outcome; to keep succeeding focus on the process that makes the outcome.", category: C.WORK },
  { text: "Your ideal partner is not someone you never disagree with but someone you are glad to disagree with.", category: C.RELATIONS },
  { text: "An open heart is the most direct path to an open mind.", category: C.WISDOM },
  { text: "If you are stuck in life travel to a place you have never heard of.", category: C.TRAVEL },
  { text: "Being curious about another person’s view is the most powerful way to change their view.", category: C.RELATIONS },
  { text: "If you don’t care about your people they won’t care about your mission.", category: C.WORK },
  { text: "To speed a meeting up require that any person who speaks must say something no one else in the room knows.", category: C.WORK },
  { text: "The rich have money. The wealthy have time. It is easier to become wealthy than rich.", category: C.MONEY },
  { text: "If you want to go fast, go alone; if you want to go further, go together.", category: C.WISDOM },
  { text: "Your best photo portrait will be taken not while you are smiling but when you are quiet a moment after you have been laughing. Use a photographer who makes you laugh.", category: C.PRACTICAL },
  { text: "If your sense of responsibility is not expanding as you grow you are not really growing.", category: C.WISDOM },
  { text: "When making plans you must allow yourself to get lost in order to find the thing you didn’t know you were looking for.", category: C.WISDOM },
  { text: "The natural state of all possessions is to need repair and maintenance. What you own will eventually own you. Choose selectively.", category: C.MONEY },
  { text: "To write about something hard to explain write a detailed letter to a friend about why it is so hard to explain, and then remove the initial “Dear Friend” part and you’ll have a great first draft.", category: C.CREATIVITY },
  { text: "Commit to doing no work no business no income one day a week. Call it a sabbath (or not). Counterintuitively, this sabbath will prove to be your most productive act all week.", category: C.HEALTH },
  { text: "Embrace pronoia which is the opposite of paranoia. Choose to believe that the entire universe is conspiring behind your back to make you a success.", category: C.WISDOM },
  { text: "Go with the option that opens up yet more options.", category: C.WISDOM },
  { text: "The first step is usually to complete the last step. You can’t load into a full dish rack.", category: C.PRACTICAL },
  { text: "When you are stuck, make a long list of everything that cannot possibly work. On that list will be a seed that leads to a solution that will work.", category: C.WORK },
  { text: "Right now no matter your age these are your golden years. The good stuff will yield golden memories and the bad stuff will yield golden lessons.", category: C.WISDOM },
  { text: "The most effective remedy for anger is delay.", category: C.WISDOM },
  { text: "Re-visioning the ordinary is what art, literature, and comedy do. You can elevate mundane details into magical wonders simply by noticing them.", category: C.CREATIVITY },
  { text: "Aim to die broke. Give to your beneficiaries before you die; it’s more fun and useful to them. Your last check should go to the funeral home and it should bounce.", category: C.MONEY },
  { text: "See that old person taking forever in line? That is the future you. Have patience.", category: C.WISDOM },
  { text: "Invent as many family rituals as you can handle with ease. Repeated consistently small routines become legendary. Anticipation is key.", category: C.FAMILY },
  { text: "The chief prevention against getting old is to remain astonished.", category: C.WISDOM },
  { text: "Art before laundry.", category: C.CREATIVITY },
  { text: "Life lessons will be presented to you in the order they are needed. Once you have truly learned a lesson you will be presented with the next one. If you are alive that means you still have lessons to learn.", category: C.WISDOM },
  { text: "Very few regrets in life are about what you did. Almost all are about what you didn’t do.", category: C.WISDOM },
  { text: "Your goal is to be able to say on the day before you die that you have fully become yourself.", category: C.WISDOM },
];
